function alpha_ddot_sol = alpha_ddot_func(theta,alpha,theta_dot,alpha_dot,u)
%ALPHA_DDOT_FUNC
%    ALPHA_DDOT_SOL = ALPHA_DDOT_FUNC(THETA,ALPHA,THETA_DOT,ALPHA_DOT,U)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    09-Jan-2025 20:50:13

t2 = -theta;
t3 = alpha+t2;
t4 = cos(t3);
alpha_ddot_sol = ((sin(alpha).*2.943e+3-t4.*u.*1.25e+3+alpha_dot.^2.*sin(alpha.*2.0-theta.*2.0).*(7.5e+1./2.0)).*(-1.0./1.5e+1))./(t4.^2.*5.0+8.0);
end
