function theta_ddot_sol = theta_ddot_func(theta,alpha,theta_dot,alpha_dot,u)
%THETA_DDOT_FUNC
%    THETA_DDOT_SOL = THETA_DDOT_FUNC(THETA,ALPHA,THETA_DOT,ALPHA_DOT,U)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    09-Jan-2025 20:50:13

t2 = -theta;
t3 = alpha+t2;
t4 = cos(t3);
theta_ddot_sol = (u.*2.0e+3-alpha_dot.^2.*sin(t3).*1.2e+2+t4.*sin(alpha).*2.943e+3)./(t4.^2.*1.2e+2+1.92e+2);
end
